services:
  cdmc:
    build:
      context: .
    image: cdmc:latest
    env_file:
      - ./backend/.env.production
    volumes:
      - cdmc_data:/var/lib/cdmc
    restart: unless-stopped
    networks:
      - default
      - nyx_bms

volumes:
  cdmc_data:

networks:
  nyx_bms:
    external: true
    name: nyx-bms_default
